---
fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    archive: "https://github.com/dfarrell07/puppet-archive"
    java: "https://github.com/puppetlabs/puppetlabs-java"
  symlinks:
    opendaylight: "#{source_dir}"
